
CREATE TABLE PLAYER
(
    USERNAME NVARCHAR(30),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE GAME
(
    GAMEID NVARCHAR(6),
    GAMESTARTDATETIME DATETIME (19),
    NUMBEROFTURNS INTEGER(1),
    GAMEOUTCOME NVARCHAR(4),
    PRIMARY KEY (USERNAME, GAMEID, GAMESTARTDATETIME),
    FOREIGN KEY (USERNAME) REFERENCES PLAYER
)

CREATE TABLE TURN
(
    TURN_NUMBER INTEGER,
    PLAYER_CHOICE NVARCHAR(8),
    CPU_CHOICE NVARCHAR(8),
    PRIMARY KEY (USERNAME, GAMEID, GAMESTARTDATETIME, TURN_NUMBER),
    FOREIGN KEY (USERNAME) REFERENCES GAME
);