CREATE TABLE USERS (
    USERNAME NVARCHAR(50),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE SELECTION (
    [DATETIME] DATETIME,
    PLAYER_SELECTION NVARCHAR(1),
    AI_SELECTION NVARCHAR(1),
    PRIMARY KEY (USERNAME, [DATETIME]),
    FOREIGN KEY (USERNAME) REFERENCES USERS
);